name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: make test

  jstest:
    name: WASM Browser Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod tidy

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Create Chrome wrapper with --no-sandbox
        run: |
          cat > /tmp/chrome-wrapper.sh << 'EOF'
          #!/bin/bash
          exec /usr/bin/google-chrome --no-sandbox "$@"
          EOF
          chmod +x /tmp/chrome-wrapper.sh

      - name: Run WASM tests
        run: make jstest
        env:
          CHROME_BIN: /tmp/chrome-wrapper.sh
