name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: make test

  jstest:
    name: WASM Browser Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod tidy

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Patch Chrome launcher to add --no-sandbox
        run: |
          # Backup the original launcher
          sudo cp /opt/google/chrome/google-chrome /opt/google/chrome/google-chrome.bak

          # Modify the launcher to inject --no-sandbox
          # This adds --no-sandbox to the exec line at the end of the script
          sudo sed -i 's/exec -a "$0" "$HERE\/chrome" "$@"/exec -a "$0" "$HERE\/chrome" --no-sandbox "$@"/' /opt/google/chrome/google-chrome

          echo "=== Modified launcher (last 5 lines) ==="
          tail -5 /opt/google/chrome/google-chrome

          echo "=== Testing modified launcher ==="
          google-chrome --version
          echo "=== Test complete ==="

      - name: Run WASM tests
        run: make jstest
